### ISSUE TITLE
Jenkinsで実施するとエラーになる

### ISSUE THREAD

**Issue by km45** [km45/complicated-querystring-visualizer#38]
```
+ make sync
docker-compose exec --user $(id -u):$(id -g) develop npm ci
Traceback (most recent call last):
  File "bin/docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 88, in main
  File "compose/cli/main.py", line 140, in perform_command
  File "compose/cli/main.py", line 486, in exec_command
  File "site-packages/dockerpty/pty.py", line 338, in start
  File "site-packages/dockerpty/io.py", line 32, in set_blocking
ValueError: file descriptor cannot be a negative integer (-1)
Failed to execute script docker-compose
make: *** [sync] Error 255
```

というエラーになる。

https://github.com/docker/compose/issues/3352
にあった `-T` を付けることで動作はするようになったが、
ローカルで実行する際に標準出力にでないようになってしまった。

そのため `-T` をつけるかどうかをスイッチング可能にしたい。

**Comment by km45** [comment]
make に `TTY` オプションを追加したので、これで要件が満たせているか確認する。

**Comment by km45** [comment]
`make sync` の実行ですぐJenkinsジョブが失敗する現象はなくなったが、
`make sync` が5分以上待っても終わらなかった。

以下のようなエラーメッセージが出ていたのでそれが原因ではないかと思う。

```
make sync TTY=false
$(misc/docker-exec-command -t false) develop npm ci
npm WARN prepare removing existing node_modules/ before installation
Unhandled rejection Error: EACCES: permission denied, mkdir '/.npm'
Unhandled rejection Error: EACCES: permission denied, mkdir '/.npm'
Unhandled rejection Error: EACCES: permission denied, mkdir '/.npm'
```

**Comment by km45** [comment]
uid / gid の問題と思われるので、
docker-compose をバージョンアップして `docker-compose exec --build-arg` による切り替えが
動作するようにしたところ問題は解消した。

本対応としては npm がキャッシュなどで使用するディレクトリを移動するなどが必要な認識。

**Comment by km45** [comment]
本 issue での対応については動作確認できたのでマージする。
